// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package adyenintegration.proxies;

/**
 * 
 */
public class Confirmation
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject confirmationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AdyenIntegration.Confirmation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		merchantReference("merchantReference"),
		skinCode("skinCode"),
		shopperLocale("shopperLocale"),
		pspReference("pspReference"),
		merchantSig("merchantSig"),
		authResult("authResult"),
		SessionId("SessionId"),
		merchantReturnData("merchantReturnData"),
		User("User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Confirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AdyenIntegration.Confirmation"));
	}

	protected Confirmation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject confirmationMendixObject)
	{
		if (confirmationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AdyenIntegration.Confirmation", confirmationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AdyenIntegration.Confirmation");

		this.confirmationMendixObject = confirmationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Confirmation.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static adyenintegration.proxies.Confirmation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return adyenintegration.proxies.Confirmation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static adyenintegration.proxies.Confirmation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new adyenintegration.proxies.Confirmation(context, mendixObject);
	}

	public static adyenintegration.proxies.Confirmation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return adyenintegration.proxies.Confirmation.initialize(context, mendixObject);
	}

	public static java.util.List<adyenintegration.proxies.Confirmation> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<adyenintegration.proxies.Confirmation> result = new java.util.ArrayList<adyenintegration.proxies.Confirmation>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AdyenIntegration.Confirmation" + xpathConstraint))
			result.add(adyenintegration.proxies.Confirmation.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of merchantReference
	 */
	public final String getmerchantReference()
	{
		return getmerchantReference(getContext());
	}

	/**
	 * @param context
	 * @return value of merchantReference
	 */
	public final String getmerchantReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.merchantReference.toString());
	}

	/**
	 * Set value of merchantReference
	 * @param merchantreference
	 */
	public final void setmerchantReference(String merchantreference)
	{
		setmerchantReference(getContext(), merchantreference);
	}

	/**
	 * Set value of merchantReference
	 * @param context
	 * @param merchantreference
	 */
	public final void setmerchantReference(com.mendix.systemwideinterfaces.core.IContext context, String merchantreference)
	{
		getMendixObject().setValue(context, MemberNames.merchantReference.toString(), merchantreference);
	}

	/**
	 * @return value of skinCode
	 */
	public final String getskinCode()
	{
		return getskinCode(getContext());
	}

	/**
	 * @param context
	 * @return value of skinCode
	 */
	public final String getskinCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.skinCode.toString());
	}

	/**
	 * Set value of skinCode
	 * @param skincode
	 */
	public final void setskinCode(String skincode)
	{
		setskinCode(getContext(), skincode);
	}

	/**
	 * Set value of skinCode
	 * @param context
	 * @param skincode
	 */
	public final void setskinCode(com.mendix.systemwideinterfaces.core.IContext context, String skincode)
	{
		getMendixObject().setValue(context, MemberNames.skinCode.toString(), skincode);
	}

	/**
	 * @return value of shopperLocale
	 */
	public final String getshopperLocale()
	{
		return getshopperLocale(getContext());
	}

	/**
	 * @param context
	 * @return value of shopperLocale
	 */
	public final String getshopperLocale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.shopperLocale.toString());
	}

	/**
	 * Set value of shopperLocale
	 * @param shopperlocale
	 */
	public final void setshopperLocale(String shopperlocale)
	{
		setshopperLocale(getContext(), shopperlocale);
	}

	/**
	 * Set value of shopperLocale
	 * @param context
	 * @param shopperlocale
	 */
	public final void setshopperLocale(com.mendix.systemwideinterfaces.core.IContext context, String shopperlocale)
	{
		getMendixObject().setValue(context, MemberNames.shopperLocale.toString(), shopperlocale);
	}

	/**
	 * @return value of pspReference
	 */
	public final String getpspReference()
	{
		return getpspReference(getContext());
	}

	/**
	 * @param context
	 * @return value of pspReference
	 */
	public final String getpspReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.pspReference.toString());
	}

	/**
	 * Set value of pspReference
	 * @param pspreference
	 */
	public final void setpspReference(String pspreference)
	{
		setpspReference(getContext(), pspreference);
	}

	/**
	 * Set value of pspReference
	 * @param context
	 * @param pspreference
	 */
	public final void setpspReference(com.mendix.systemwideinterfaces.core.IContext context, String pspreference)
	{
		getMendixObject().setValue(context, MemberNames.pspReference.toString(), pspreference);
	}

	/**
	 * @return value of merchantSig
	 */
	public final String getmerchantSig()
	{
		return getmerchantSig(getContext());
	}

	/**
	 * @param context
	 * @return value of merchantSig
	 */
	public final String getmerchantSig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.merchantSig.toString());
	}

	/**
	 * Set value of merchantSig
	 * @param merchantsig
	 */
	public final void setmerchantSig(String merchantsig)
	{
		setmerchantSig(getContext(), merchantsig);
	}

	/**
	 * Set value of merchantSig
	 * @param context
	 * @param merchantsig
	 */
	public final void setmerchantSig(com.mendix.systemwideinterfaces.core.IContext context, String merchantsig)
	{
		getMendixObject().setValue(context, MemberNames.merchantSig.toString(), merchantsig);
	}

	/**
	 * @return value of authResult
	 */
	public final String getauthResult()
	{
		return getauthResult(getContext());
	}

	/**
	 * @param context
	 * @return value of authResult
	 */
	public final String getauthResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.authResult.toString());
	}

	/**
	 * Set value of authResult
	 * @param authresult
	 */
	public final void setauthResult(String authresult)
	{
		setauthResult(getContext(), authresult);
	}

	/**
	 * Set value of authResult
	 * @param context
	 * @param authresult
	 */
	public final void setauthResult(com.mendix.systemwideinterfaces.core.IContext context, String authresult)
	{
		getMendixObject().setValue(context, MemberNames.authResult.toString(), authresult);
	}

	/**
	 * @return value of SessionId
	 */
	public final String getSessionId()
	{
		return getSessionId(getContext());
	}

	/**
	 * @param context
	 * @return value of SessionId
	 */
	public final String getSessionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SessionId.toString());
	}

	/**
	 * Set value of SessionId
	 * @param sessionid
	 */
	public final void setSessionId(String sessionid)
	{
		setSessionId(getContext(), sessionid);
	}

	/**
	 * Set value of SessionId
	 * @param context
	 * @param sessionid
	 */
	public final void setSessionId(com.mendix.systemwideinterfaces.core.IContext context, String sessionid)
	{
		getMendixObject().setValue(context, MemberNames.SessionId.toString(), sessionid);
	}

	/**
	 * @return value of merchantReturnData
	 */
	public final String getmerchantReturnData()
	{
		return getmerchantReturnData(getContext());
	}

	/**
	 * @param context
	 * @return value of merchantReturnData
	 */
	public final String getmerchantReturnData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.merchantReturnData.toString());
	}

	/**
	 * Set value of merchantReturnData
	 * @param merchantreturndata
	 */
	public final void setmerchantReturnData(String merchantreturndata)
	{
		setmerchantReturnData(getContext(), merchantreturndata);
	}

	/**
	 * Set value of merchantReturnData
	 * @param context
	 * @param merchantreturndata
	 */
	public final void setmerchantReturnData(com.mendix.systemwideinterfaces.core.IContext context, String merchantreturndata)
	{
		getMendixObject().setValue(context, MemberNames.merchantReturnData.toString(), merchantreturndata);
	}

	/**
	 * @return value of User
	 */
	public final String getUser()
	{
		return getUser(getContext());
	}

	/**
	 * @param context
	 * @return value of User
	 */
	public final String getUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.User.toString());
	}

	/**
	 * Set value of User
	 * @param user
	 */
	public final void setUser(String user)
	{
		setUser(getContext(), user);
	}

	/**
	 * Set value of User
	 * @param context
	 * @param user
	 */
	public final void setUser(com.mendix.systemwideinterfaces.core.IContext context, String user)
	{
		getMendixObject().setValue(context, MemberNames.User.toString(), user);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return confirmationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final adyenintegration.proxies.Confirmation that = (adyenintegration.proxies.Confirmation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AdyenIntegration.Confirmation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
