// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package adyenintegration.proxies;

/**
 * 
 */
public class PaymentSettings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject paymentSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AdyenIntegration.PaymentSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		merchantAccount("merchantAccount"),
		skinCode("skinCode"),
		currencyCode("currencyCode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PaymentSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AdyenIntegration.PaymentSettings"));
	}

	protected PaymentSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject paymentSettingsMendixObject)
	{
		if (paymentSettingsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AdyenIntegration.PaymentSettings", paymentSettingsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AdyenIntegration.PaymentSettings");

		this.paymentSettingsMendixObject = paymentSettingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PaymentSettings.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static adyenintegration.proxies.PaymentSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return adyenintegration.proxies.PaymentSettings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static adyenintegration.proxies.PaymentSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new adyenintegration.proxies.PaymentSettings(context, mendixObject);
	}

	public static adyenintegration.proxies.PaymentSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return adyenintegration.proxies.PaymentSettings.initialize(context, mendixObject);
	}

	public static java.util.List<adyenintegration.proxies.PaymentSettings> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<adyenintegration.proxies.PaymentSettings> result = new java.util.ArrayList<adyenintegration.proxies.PaymentSettings>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AdyenIntegration.PaymentSettings" + xpathConstraint))
			result.add(adyenintegration.proxies.PaymentSettings.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of merchantAccount
	 */
	public final String getmerchantAccount()
	{
		return getmerchantAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of merchantAccount
	 */
	public final String getmerchantAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.merchantAccount.toString());
	}

	/**
	 * Set value of merchantAccount
	 * @param merchantaccount
	 */
	public final void setmerchantAccount(String merchantaccount)
	{
		setmerchantAccount(getContext(), merchantaccount);
	}

	/**
	 * Set value of merchantAccount
	 * @param context
	 * @param merchantaccount
	 */
	public final void setmerchantAccount(com.mendix.systemwideinterfaces.core.IContext context, String merchantaccount)
	{
		getMendixObject().setValue(context, MemberNames.merchantAccount.toString(), merchantaccount);
	}

	/**
	 * @return value of skinCode
	 */
	public final String getskinCode()
	{
		return getskinCode(getContext());
	}

	/**
	 * @param context
	 * @return value of skinCode
	 */
	public final String getskinCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.skinCode.toString());
	}

	/**
	 * Set value of skinCode
	 * @param skincode
	 */
	public final void setskinCode(String skincode)
	{
		setskinCode(getContext(), skincode);
	}

	/**
	 * Set value of skinCode
	 * @param context
	 * @param skincode
	 */
	public final void setskinCode(com.mendix.systemwideinterfaces.core.IContext context, String skincode)
	{
		getMendixObject().setValue(context, MemberNames.skinCode.toString(), skincode);
	}

	/**
	 * @return value of currencyCode
	 */
	public final String getcurrencyCode()
	{
		return getcurrencyCode(getContext());
	}

	/**
	 * @param context
	 * @return value of currencyCode
	 */
	public final String getcurrencyCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.currencyCode.toString());
	}

	/**
	 * Set value of currencyCode
	 * @param currencycode
	 */
	public final void setcurrencyCode(String currencycode)
	{
		setcurrencyCode(getContext(), currencycode);
	}

	/**
	 * Set value of currencyCode
	 * @param context
	 * @param currencycode
	 */
	public final void setcurrencyCode(com.mendix.systemwideinterfaces.core.IContext context, String currencycode)
	{
		getMendixObject().setValue(context, MemberNames.currencyCode.toString(), currencycode);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return paymentSettingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final adyenintegration.proxies.PaymentSettings that = (adyenintegration.proxies.PaymentSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AdyenIntegration.PaymentSettings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
