// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package adyenintegration.proxies;

/**
 * 
 */
public class Payment
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject paymentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AdyenIntegration.Payment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		merchantSig("merchantSig"),
		sessionValidity("sessionValidity"),
		shipBeforeDate("shipBeforeDate"),
		shopperLocale("shopperLocale"),
		merchantAccount("merchantAccount"),
		paymentAmount("paymentAmount"),
		currencyCode("currencyCode"),
		skinCode("skinCode"),
		merchantReference("merchantReference"),
		shopperReference("shopperReference"),
		recurringContract("recurringContract"),
		shopperEmail("shopperEmail"),
		merchantReturnData("merchantReturnData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Payment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AdyenIntegration.Payment"));
	}

	protected Payment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject paymentMendixObject)
	{
		if (paymentMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AdyenIntegration.Payment", paymentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AdyenIntegration.Payment");

		this.paymentMendixObject = paymentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Payment.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static adyenintegration.proxies.Payment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return adyenintegration.proxies.Payment.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static adyenintegration.proxies.Payment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new adyenintegration.proxies.Payment(context, mendixObject);
	}

	public static adyenintegration.proxies.Payment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return adyenintegration.proxies.Payment.initialize(context, mendixObject);
	}

	public static java.util.List<adyenintegration.proxies.Payment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<adyenintegration.proxies.Payment> result = new java.util.ArrayList<adyenintegration.proxies.Payment>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AdyenIntegration.Payment" + xpathConstraint))
			result.add(adyenintegration.proxies.Payment.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of merchantSig
	 */
	public final String getmerchantSig()
	{
		return getmerchantSig(getContext());
	}

	/**
	 * @param context
	 * @return value of merchantSig
	 */
	public final String getmerchantSig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.merchantSig.toString());
	}

	/**
	 * Set value of merchantSig
	 * @param merchantsig
	 */
	public final void setmerchantSig(String merchantsig)
	{
		setmerchantSig(getContext(), merchantsig);
	}

	/**
	 * Set value of merchantSig
	 * @param context
	 * @param merchantsig
	 */
	public final void setmerchantSig(com.mendix.systemwideinterfaces.core.IContext context, String merchantsig)
	{
		getMendixObject().setValue(context, MemberNames.merchantSig.toString(), merchantsig);
	}

	/**
	 * @return value of sessionValidity
	 */
	public final String getsessionValidity()
	{
		return getsessionValidity(getContext());
	}

	/**
	 * @param context
	 * @return value of sessionValidity
	 */
	public final String getsessionValidity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.sessionValidity.toString());
	}

	/**
	 * Set value of sessionValidity
	 * @param sessionvalidity
	 */
	public final void setsessionValidity(String sessionvalidity)
	{
		setsessionValidity(getContext(), sessionvalidity);
	}

	/**
	 * Set value of sessionValidity
	 * @param context
	 * @param sessionvalidity
	 */
	public final void setsessionValidity(com.mendix.systemwideinterfaces.core.IContext context, String sessionvalidity)
	{
		getMendixObject().setValue(context, MemberNames.sessionValidity.toString(), sessionvalidity);
	}

	/**
	 * @return value of shipBeforeDate
	 */
	public final String getshipBeforeDate()
	{
		return getshipBeforeDate(getContext());
	}

	/**
	 * @param context
	 * @return value of shipBeforeDate
	 */
	public final String getshipBeforeDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.shipBeforeDate.toString());
	}

	/**
	 * Set value of shipBeforeDate
	 * @param shipbeforedate
	 */
	public final void setshipBeforeDate(String shipbeforedate)
	{
		setshipBeforeDate(getContext(), shipbeforedate);
	}

	/**
	 * Set value of shipBeforeDate
	 * @param context
	 * @param shipbeforedate
	 */
	public final void setshipBeforeDate(com.mendix.systemwideinterfaces.core.IContext context, String shipbeforedate)
	{
		getMendixObject().setValue(context, MemberNames.shipBeforeDate.toString(), shipbeforedate);
	}

	/**
	 * @return value of shopperLocale
	 */
	public final String getshopperLocale()
	{
		return getshopperLocale(getContext());
	}

	/**
	 * @param context
	 * @return value of shopperLocale
	 */
	public final String getshopperLocale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.shopperLocale.toString());
	}

	/**
	 * Set value of shopperLocale
	 * @param shopperlocale
	 */
	public final void setshopperLocale(String shopperlocale)
	{
		setshopperLocale(getContext(), shopperlocale);
	}

	/**
	 * Set value of shopperLocale
	 * @param context
	 * @param shopperlocale
	 */
	public final void setshopperLocale(com.mendix.systemwideinterfaces.core.IContext context, String shopperlocale)
	{
		getMendixObject().setValue(context, MemberNames.shopperLocale.toString(), shopperlocale);
	}

	/**
	 * @return value of merchantAccount
	 */
	public final String getmerchantAccount()
	{
		return getmerchantAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of merchantAccount
	 */
	public final String getmerchantAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.merchantAccount.toString());
	}

	/**
	 * Set value of merchantAccount
	 * @param merchantaccount
	 */
	public final void setmerchantAccount(String merchantaccount)
	{
		setmerchantAccount(getContext(), merchantaccount);
	}

	/**
	 * Set value of merchantAccount
	 * @param context
	 * @param merchantaccount
	 */
	public final void setmerchantAccount(com.mendix.systemwideinterfaces.core.IContext context, String merchantaccount)
	{
		getMendixObject().setValue(context, MemberNames.merchantAccount.toString(), merchantaccount);
	}

	/**
	 * @return value of paymentAmount
	 */
	public final String getpaymentAmount()
	{
		return getpaymentAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of paymentAmount
	 */
	public final String getpaymentAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.paymentAmount.toString());
	}

	/**
	 * Set value of paymentAmount
	 * @param paymentamount
	 */
	public final void setpaymentAmount(String paymentamount)
	{
		setpaymentAmount(getContext(), paymentamount);
	}

	/**
	 * Set value of paymentAmount
	 * @param context
	 * @param paymentamount
	 */
	public final void setpaymentAmount(com.mendix.systemwideinterfaces.core.IContext context, String paymentamount)
	{
		getMendixObject().setValue(context, MemberNames.paymentAmount.toString(), paymentamount);
	}

	/**
	 * @return value of currencyCode
	 */
	public final String getcurrencyCode()
	{
		return getcurrencyCode(getContext());
	}

	/**
	 * @param context
	 * @return value of currencyCode
	 */
	public final String getcurrencyCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.currencyCode.toString());
	}

	/**
	 * Set value of currencyCode
	 * @param currencycode
	 */
	public final void setcurrencyCode(String currencycode)
	{
		setcurrencyCode(getContext(), currencycode);
	}

	/**
	 * Set value of currencyCode
	 * @param context
	 * @param currencycode
	 */
	public final void setcurrencyCode(com.mendix.systemwideinterfaces.core.IContext context, String currencycode)
	{
		getMendixObject().setValue(context, MemberNames.currencyCode.toString(), currencycode);
	}

	/**
	 * @return value of skinCode
	 */
	public final String getskinCode()
	{
		return getskinCode(getContext());
	}

	/**
	 * @param context
	 * @return value of skinCode
	 */
	public final String getskinCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.skinCode.toString());
	}

	/**
	 * Set value of skinCode
	 * @param skincode
	 */
	public final void setskinCode(String skincode)
	{
		setskinCode(getContext(), skincode);
	}

	/**
	 * Set value of skinCode
	 * @param context
	 * @param skincode
	 */
	public final void setskinCode(com.mendix.systemwideinterfaces.core.IContext context, String skincode)
	{
		getMendixObject().setValue(context, MemberNames.skinCode.toString(), skincode);
	}

	/**
	 * @return value of merchantReference
	 */
	public final String getmerchantReference()
	{
		return getmerchantReference(getContext());
	}

	/**
	 * @param context
	 * @return value of merchantReference
	 */
	public final String getmerchantReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.merchantReference.toString());
	}

	/**
	 * Set value of merchantReference
	 * @param merchantreference
	 */
	public final void setmerchantReference(String merchantreference)
	{
		setmerchantReference(getContext(), merchantreference);
	}

	/**
	 * Set value of merchantReference
	 * @param context
	 * @param merchantreference
	 */
	public final void setmerchantReference(com.mendix.systemwideinterfaces.core.IContext context, String merchantreference)
	{
		getMendixObject().setValue(context, MemberNames.merchantReference.toString(), merchantreference);
	}

	/**
	 * @return value of shopperReference
	 */
	public final String getshopperReference()
	{
		return getshopperReference(getContext());
	}

	/**
	 * @param context
	 * @return value of shopperReference
	 */
	public final String getshopperReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.shopperReference.toString());
	}

	/**
	 * Set value of shopperReference
	 * @param shopperreference
	 */
	public final void setshopperReference(String shopperreference)
	{
		setshopperReference(getContext(), shopperreference);
	}

	/**
	 * Set value of shopperReference
	 * @param context
	 * @param shopperreference
	 */
	public final void setshopperReference(com.mendix.systemwideinterfaces.core.IContext context, String shopperreference)
	{
		getMendixObject().setValue(context, MemberNames.shopperReference.toString(), shopperreference);
	}

	/**
	 * @return value of recurringContract
	 */
	public final String getrecurringContract()
	{
		return getrecurringContract(getContext());
	}

	/**
	 * @param context
	 * @return value of recurringContract
	 */
	public final String getrecurringContract(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.recurringContract.toString());
	}

	/**
	 * Set value of recurringContract
	 * @param recurringcontract
	 */
	public final void setrecurringContract(String recurringcontract)
	{
		setrecurringContract(getContext(), recurringcontract);
	}

	/**
	 * Set value of recurringContract
	 * @param context
	 * @param recurringcontract
	 */
	public final void setrecurringContract(com.mendix.systemwideinterfaces.core.IContext context, String recurringcontract)
	{
		getMendixObject().setValue(context, MemberNames.recurringContract.toString(), recurringcontract);
	}

	/**
	 * @return value of shopperEmail
	 */
	public final String getshopperEmail()
	{
		return getshopperEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of shopperEmail
	 */
	public final String getshopperEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.shopperEmail.toString());
	}

	/**
	 * Set value of shopperEmail
	 * @param shopperemail
	 */
	public final void setshopperEmail(String shopperemail)
	{
		setshopperEmail(getContext(), shopperemail);
	}

	/**
	 * Set value of shopperEmail
	 * @param context
	 * @param shopperemail
	 */
	public final void setshopperEmail(com.mendix.systemwideinterfaces.core.IContext context, String shopperemail)
	{
		getMendixObject().setValue(context, MemberNames.shopperEmail.toString(), shopperemail);
	}

	/**
	 * @return value of merchantReturnData
	 */
	public final String getmerchantReturnData()
	{
		return getmerchantReturnData(getContext());
	}

	/**
	 * @param context
	 * @return value of merchantReturnData
	 */
	public final String getmerchantReturnData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.merchantReturnData.toString());
	}

	/**
	 * Set value of merchantReturnData
	 * @param merchantreturndata
	 */
	public final void setmerchantReturnData(String merchantreturndata)
	{
		setmerchantReturnData(getContext(), merchantreturndata);
	}

	/**
	 * Set value of merchantReturnData
	 * @param context
	 * @param merchantreturndata
	 */
	public final void setmerchantReturnData(com.mendix.systemwideinterfaces.core.IContext context, String merchantreturndata)
	{
		getMendixObject().setValue(context, MemberNames.merchantReturnData.toString(), merchantreturndata);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return paymentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final adyenintegration.proxies.Payment that = (adyenintegration.proxies.Payment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AdyenIntegration.Payment";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
