// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package deeplink.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DeepLink module

	public static boolean bCo_Deeplink_SetAttributes(IContext context, deeplink.proxies.DeepLink _deepLink)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("DeepLink", _deepLink == null ? null : _deepLink.getMendixObject());
			return (Boolean)Core.execute(context, "DeepLink.BCo_Deeplink_SetAttributes", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void clearOldPendingLinks(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "DeepLink.ClearOldPendingLinks", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void createDeeplinkConfig(IContext context, String _name, String _microflow, String _objectType, String _objectAttr, boolean _allowGuests, boolean _useStringArg, boolean _useAsHome, String _indexPage, boolean _includeGetParams, boolean _separateGetParams, boolean _objectAsParameter)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Name", _name);
			params.put("Microflow", _microflow);
			params.put("ObjectType", _objectType);
			params.put("ObjectAttr", _objectAttr);
			params.put("AllowGuests", _allowGuests);
			params.put("UseStringArg", _useStringArg);
			params.put("UseAsHome", _useAsHome);
			params.put("IndexPage", _indexPage);
			params.put("IncludeGetParams", _includeGetParams);
			params.put("SeparateGetParams", _separateGetParams);
			params.put("ObjectAsParameter", _objectAsParameter);
			Core.execute(context, "DeepLink.CreateDeeplinkConfig", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static boolean deepLinkHome(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			return (Boolean)Core.execute(context, "DeepLink.DeepLinkHome", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static java.util.List<deeplink.proxies.Attribute> dSL_Attribute(IContext context, deeplink.proxies.DeepLink _deepLink)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("DeepLink", _deepLink == null ? null : _deepLink.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "DeepLink.DSL_Attribute", params);
			java.util.List<deeplink.proxies.Attribute> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<deeplink.proxies.Attribute>();
				for (IMendixObject obj : objs)
					result.add(deeplink.proxies.Attribute.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_AttributeSelect(IContext context, deeplink.proxies.Attribute _attribute, deeplink.proxies.DeepLink _deepLink)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Attribute", _attribute == null ? null : _attribute.getMendixObject());
			params.put("DeepLink", _deepLink == null ? null : _deepLink.getMendixObject());
			Core.execute(context, "DeepLink.IVK_AttributeSelect", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_EntitySelect(IContext context, deeplink.proxies.Entity _entity, deeplink.proxies.DeepLink _deepLink)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Entity", _entity == null ? null : _entity.getMendixObject());
			params.put("DeepLink", _deepLink == null ? null : _deepLink.getMendixObject());
			Core.execute(context, "DeepLink.IVK_EntitySelect", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_MicroflowSelect(IContext context, deeplink.proxies.Microflow _microflow, deeplink.proxies.DeepLink _deepLink)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Microflow", _microflow == null ? null : _microflow.getMendixObject());
			params.put("DeepLink", _deepLink == null ? null : _deepLink.getMendixObject());
			Core.execute(context, "DeepLink.IVK_MicroflowSelect", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_ShowEntitySelect(IContext context, deeplink.proxies.DeepLink _deepLink)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("DeepLink", _deepLink == null ? null : _deepLink.getMendixObject());
			Core.execute(context, "DeepLink.IVK_ShowEntitySelect", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_ShowMicroflowSelect(IContext context, deeplink.proxies.DeepLink _deepLink)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("DeepLink", _deepLink == null ? null : _deepLink.getMendixObject());
			Core.execute(context, "DeepLink.IVK_ShowMicroflowSelect", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void oCh_Name(IContext context, deeplink.proxies.DeepLink _deepLink)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("DeepLink", _deepLink == null ? null : _deepLink.getMendixObject());
			Core.execute(context, "DeepLink.OCh_Name", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void reloadMetaData(IContext context, deeplink.proxies.DeepLink _deepLink)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("DeepLink", _deepLink == null ? null : _deepLink.getMendixObject());
			Core.execute(context, "DeepLink.ReloadMetaData", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void showDeeplinkConfigurationOverview(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "DeepLink.ShowDeeplinkConfigurationOverview", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static boolean startDeeplink(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			return (Boolean)Core.execute(context, "DeepLink.StartDeeplink", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}