// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package adyenintegration.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the AdyenIntegration module

	public static String getHMAC_Key()
	{
		return (String)Core.getConfiguration().getConstantValue("AdyenIntegration.HMAC_Key");
	}
}