// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package deeplink.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DeepLink module

	public static String getIndexPage()
	{
		return (String)Core.getConfiguration().getConstantValue("DeepLink.IndexPage");
	}

	public static String getLoginLocation()
	{
		return (String)Core.getConfiguration().getConstantValue("DeepLink.LoginLocation");
	}
}